[project]
name = "sterics-descriptors"
version = "0.1.0"
description = "Sterics descriptors project"
authors = [
    { name = "Alessio Prunotto", email = "alessio.prunotto@gmail.com" }
]
license = {text = "MIT"}
readme = "README.md"

dependencies = [
    "rdkit",
    "pandas",
    "numpy",
    "requests",
    "seaborn",
    "matplotlib",
    "tqdm",
    # Add any other dependencies your project needs here
]

[tool.setuptools]
packages = ["scripts"]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
